config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/mattiaBarbo/SQAaaS_Test:
      branch: main
      repo: https://github.com/mattiaBarbo/SQAaaS_Test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-bistre-hedgehog.sh
        container: qc.acc_sickly-thistle-bear
  QC.Doc:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-brass-kakapo.sh
        container: qc.doc_squeaky-orange-numbat
      github.com/mattiaBarbo/SQAaaS_Test git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-brass-hound.sh
        container: qc.doc_gamy-aqua-havanese
      github.com/mattiaBarbo/SQAaaS_Test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-rust-kangaroo.sh
        container: qc.doc_freaky-khaki-dog
  QC.Lic:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-russet-tiger.sh
        container: qc.lic_fuzzy-chocolate-spitz
  QC.Sec:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-aquamarine-tang.sh
        container: qc.sec_slaphappy-asparagus-collie
  QC.Sty:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-harlequin-drever.sh
        container: qc.sty_chummy-gamboge-serval
  QC.Uni:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test commands:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-bistre-frigatebird.sh
        container: qc.uni_droopy-maroon-dolphin
  QC.Ver:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-beige-armadillo.sh
        container: qc.ver_bluesy-sapphire-lemur
timeout: 5400
